### ISSUE TITLE
Show Terminated Agreements in the Dashboard

### ISSUE THREAD

**Issue by varatep** [open-horizon/anax-ui#61]

**Comment by varatep** [comment]
@bmpotter @linggao 
For showing data of terminated agreements, do we care about _all_ terminated agreements for every service, or only the most recent for each service?

**Comment by varatep** [comment]
Update on this: I have completed a view that displays _all_ terminated agreements. Currently for my RPi, ~400. This is pretty slow. I'll need to add pagination to improve rendering speeds, unless we only care about the most recent terminated agreements for each service.

**Comment by linggao** [comment]
It's good to show all so that we know what has happened. Paging would be good, please show the most recent archived agreements first.

**Comment by varatep** [comment]
@bmpotter @linggao Example of information displayed for a given terminated agreement. Let me know if you guys would like a different format or other data displayed.

![image](https://user-images.githubusercontent.com/3941301/27989516-15ee20e0-63ef-11e7-8751-3f5e6db89bd0.png)

**Comment by varatep** [comment]
@bmpotter Does the API currently support server-side paging?

**Comment by dabooz** [comment]
Couple points:
0) Workload terminated time has the word terminated shown twice. :-)
1) Is it possible (do we want to?) to have the terminated agreements shown in  summary form with a widget that would display more details when you click on it? I am thinking that fields like Proposal, Proposal Sig, and Terminated Reason, could be relegated to the detail display. If we gave this more thought, we might decide that we could move more fields to a details section (counterparty address, agreement protocol terminated time and workload terminated time could move to the details section too). And in the details section maybe we could also format the proposal instead of showing it as a long string.
2) Fields AgreementDataReceivedTime, MeteringNotificationMsg are missing. Further, I am adding new fields all the time to the agreement records in the database. How do we get new fields included in the UI (either in the summary section or the details section)? Can the UI be coded to show (in the detail view only) everything that comes back in the API, not just the fields it knows about?

**Comment by varatep** [comment]
@dabooz Thanks for catching that!

For pt 1, I think some sort of detailed display/page would be great to show in-depth data on the certain agreement. We'd have to discuss with @linggao wrt to this since it is my understanding that she wants all data to be shown in a segment. We would also have to discuss which properties we want to show in the minified version versus the full detailed version.

Pt 2, yes, we can do that. If we go with part 1, we'd need to have a list of properties that are displayed in the short version so I can filter those out anyways.

**Comment by varatep** [comment]
@bmpotter @linggao 
Here are the items I currently filter through, where the variable `ag` is the terminated agreement:

```
ag.current_agreement_id
ag.name
ag.sensor_url
ag.consumer_id
ag.counterparty_address
ag.proposal
ag.proposal_sig
ag.terminated_description
ag.terminated_reason
```

Let me know if there is anything else you want me to add to this.

**Comment by bmpotter** [comment]
That list above looks pretty good. I would **remove** proposal_sig and **add** agreement_protocol and all of the times (creation, accepted, etc.).

**Comment by varatep** [comment]
@bmpotter Made those changes in this commit https://github.com/open-horizon/anax-ui/pull/73/commits/596c7f9256aa2aa72dcc328d38f7fd3da8f2736f
