### ISSUE TITLE
refreshing pages goes back to the first page

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax-ui#97]
In the registration process, finished the first page and proceeded to the second and third page, now refresh the pages (page 2 or 3) from the browser refresh button, the ui will go back to the first page instead of staying at the same page.

**Comment by michaeldye** [comment]
@varatep : This is caused by the same problem as https://github.com/open-horizon/anax/issues/79 . There was a PR a while back that had a kind of usability workaround for this, it had links open in new tabs (which I think is the wrong way to fix the problem). The root of it is something I caused way back when I wrote the initial SPA: I didn't get the routing and history state saving right back then (probably related to this https://github.com/open-horizon/anax-ui/blob/master/src/index.js#L20). If you dig into that issue you can likely put all of these browser history issues to rest.

**Comment by linggao** [comment]
The problem still exists.

**Comment by varatep** [comment]
@bmpotter @linggao With respect to refreshing, it's similar to re-opening the tab. In order to keep the state information, we would have to store the current state information inside the browser's local storage. Previously, we were trying to stay away from using local storage. We can have a discussion if keeping state is important during a refresh/re-visit and what kind of information we can keep in the local storage. We most likely would need the user to re-authenticate, since keeping auth information in the browser is a no-no for us. Let me know if our needs and requirements have changed.

**Comment by bmpotter** [comment]
Of the remaining reg UI  bugs, this is the lowest priority, since there is not usually a need to refresh the browser page while going thru registration. So i'm icebox-ing this one.
